sources:
    drodo:
        base: "http://gemtd.ppbizon.com/"
        endpoints:
            gemtd:
                goods: "gemtd/201803/goods/list/@{steam_id}"
                heroes: "gemtd/202203/heros/get/@{steam_id}"
                leaderboard: "gemtd/leaderboard/@{steam_id}"
    steam:
        base: "http://api.steampowered.com/"
        endpoints:
            player_summaries: "ISteamUser/GetPlayerSummaries/v0002/?key={key}&steamids={steam_ids}"

default_source: drodo
